In [4]:
#Write a program to distinguish between Array Indexing and Fancy Indexing.

import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Array Indexing")
print( arr[2])

fancy = np.array([1,3,5])
print("Fancy Indexing")
print(arr[fancy])

Array Indexing
3
Fancy Indexing
[2 4 6]


In [8]:
#Execute the 2D array Slicing.

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print("Original Array")
print(arr)

print("\nSliced Array")
print(arr[1:3, 0:2]) 

Original Array
[[1 2 3]
 [4 5 6]]

Sliced Array
[[4 5]]


In [9]:
#Create the 5-Dimensional arrays using ‘ndmin’.

import numpy as np

arr=np.array([1,2,3], ndmin=5)
print(arr)

[[[[[1 2 3]]]]]


In [11]:
#Reshape the array from 1-D to 2-D array.

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape((2,4)))

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
#Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
stack = np.stack((arr1, arr2))
print(stack)


#hstack()
print("------------------")
hstack = np.hstack((arr1, arr2))
print(hstack)

#vstack()
print("-------------------")
vstack = np.vstack((arr1, arr2))
print(vstack)


#dstack
print("--------------------------")
dstack = np.dstack((arr1, arr2))
print(dstack)

[[1 2 3]
 [4 5 6]]
------------------
[1 2 3 4 5 6]
-------------------
[[1 2 3]
 [4 5 6]]
--------------------------
[[[1 4]
  [2 5]
  [3 6]]]


In [23]:
#Perform the searchsort method in Numpy array.
import numpy as np
arr = np.array([10,32,45,67,88,43])
num = 45
search = np.searchsorted(arr, num)
print(search)

2


In [27]:
#Create Numpy Structured array using your domain features.

import numpy as np

athlete_dtype = np.dtype([
    ('name', 'U50'),('age', int),('team', 'U50'),('points', float),('assists', int)       
])

#numpy array with sample data
athletes_data = np.array([
    ('John Doe', 25, 'Team A', 18.5, 4),
    ('Jane Smith', 22, 'Team B', 15.2, 2),
    ('Mike Johnson', 28, 'Team A', 20.1, 6),
], dtype=athlete_dtype)

print("Structured Array:")
print(athletes_data)
print("\nFirst Athlete:")
print("Name:", athletes_data[0]['name'])
print("Age:", athletes_data[0]['age'])
print("Team:", athletes_data[0]['team'])
print("Points: ",athletes_data[0]['points'])
print("Assists: ",athletes_data[0]['assists'])

Structured Array:
[('John Doe', 25, 'Team A', 18.5, 4) ('Jane Smith', 22, 'Team B', 15.2, 2)
 ('Mike Johnson', 28, 'Team A', 20.1, 6)]

First Athlete:
Name: John Doe
Age: 25
Team: Team A
Points:  18.5
Assists:  4


In [33]:
#Create Data frame using List and Dictionary.

import pandas as pd

data_list_of_dicts = [
    {'Name': 'Alice', 'Age': 28},
    {'Name': 'Bob', 'Age': 22},
    {'Name': 'Charlie', 'Age': 25}
]

df_from_list_of_dicts = pd.DataFrame(data_list_of_dicts)

print("DataFrame created from a list of dictionaries:")
print(df_from_list_of_dicts)

DataFrame created from a list of dictionaries:
      Name  Age
0    Alice   28
1      Bob   22
2  Charlie   25


In [44]:

#Create Data frame on your Domain area and perform the following operations to find and eliminate the
#missing data from the dataset.


import pandas as pd
import numpy as np


data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age': [25, np.nan, 30, 22, 28],
        'Salary': [50000, 60000, np.nan, np.nan, 75000]}
df = pd.DataFrame(data)


print("Original DataFrame:")
print(df)


print("\nUsing isnull() to check for missing values:")
print(df.isnull())

print("\nUsing notnull() to check for non-missing values:")
print(df.notnull())


df_dropped = df.dropna()
print("\nUsing dropna() to remove rows with missing values:")
print(df_dropped)


df_filled = df.fillna({'Age': df['Age'].mean(), 'Salary': df['Salary'].median()})
print("\nUsing fillna() to fill missing values:")
print(df_filled)


df_replaced = df.replace({'Alice': 'Alicia', 'Bob': 'Bobby'})
print("\nUsing replace() to replace specific values:")
print(df_replaced)


df = df.infer_objects()

df_interpolated = df.interpolate()
print("\nUsing interpolate() to fill missing values with interpolation:")
print(df_interpolated)

Original DataFrame:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN  60000.0
2  Charlie  30.0      NaN
3    David  22.0      NaN
4      Eva  28.0  75000.0

Using isnull() to check for missing values:
    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False    True
4  False  False   False

Using notnull() to check for non-missing values:
   Name    Age  Salary
0  True   True    True
1  True  False    True
2  True   True   False
3  True   True   False
4  True   True    True

Using dropna() to remove rows with missing values:
    Name   Age   Salary
0  Alice  25.0  50000.0
4    Eva  28.0  75000.0

Using fillna() to fill missing values:
      Name    Age   Salary
0    Alice  25.00  50000.0
1      Bob  26.25  60000.0
2  Charlie  30.00  60000.0
3    David  22.00  60000.0
4      Eva  28.00  75000.0

Using replace() to replace specific values:
      Name   Age   Salary
0   Alicia  25.0  50000.0
1    Bobby   NaN  60000.

C:\Users\aksha\AppData\Local\Temp\ipykernel_10000\1374329613.py:43: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate()


In [43]:
#Perform the Hierarchical Indexing in the above created dataset.


import pandas as pd
import numpy as np

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age': [25, np.nan, 30, 22, 28],
        'Salary': [50000, 60000, np.nan, np.nan, 75000]}
df = pd.DataFrame(data)

df['Department'] = ['HR', 'IT', 'Finance', 'IT', 'Marketing']

df.set_index(['Department', 'Name'], inplace=True)

print("DataFrame with Hierarchical Indexing:")
print(df)

DataFrame with Hierarchical Indexing:
                     Age   Salary
Department Name                  
HR         Alice    25.0  50000.0
IT         Bob       NaN  60000.0
Finance    Charlie  30.0      NaN
IT         David    22.0      NaN
Marketing  Eva      28.0  75000.0
